version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: copilot_auth_postgres
    environment:
      POSTGRES_DB: copilot_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - copilot_auth_data:/var/lib/postgresql/data
    networks:
      - copilot-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/copilot_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      APP_JWT_SECRET: 473f314815a9826fc0e1499530433bf6cacf87d972e0cc7b4c6351a7980e2f6d
      APP_JWT_EXPIRATION-SECOND: 3600
    ports:
      - "8081:8081"
    networks:
      - copilot-net

  ai-service:
    build: ./ai-service
    container_name: ai-service
    depends_on:
      - auth-service
    environment:
      APP_JWT_SECRET: 473f314815a9826fc0e1499530433bf6cacf87d972e0cc7b4c6351a7980e2f6d
      OPENAI_API_KEY: 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
    ports:
      - "8082:8082"
    networks:
      - copilot-net

  frontend:
    build: ./CHAT-WEBAPP
    container_name: copilot-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_AUTH_SERVICE_URL: /api
      VITE_AI_SERVICE_URL: /api
    depends_on:
      - auth-service
      - ai-service
    networks:
      - copilot-net

  nginx:
    image: nginx:latest
    container_name: copilot-nginx
    depends_on:
      - frontend
      - auth-service
      - ai-service
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - copilot-net



networks:
  copilot-net:

volumes:
  copilot_auth_data:
