server:
  port: 8082

spring:
  application:
    name: ai-service

  ai:
    openai:
      baseUrl: https://api.groq.com/openai/v1
      apiKey: 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
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7


  mail:
    host: smtp.mail.ru
    port: 465
    username: copilot-assissant@mail.ru
    password: H1tJIESSXQ9wSjpcCKc3
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8
    test-connection: false

app:
  jwt:
    secret: 473f314815a9826fc0e1499530433bf6cacf87d972e0cc7b4c6351a7980e2f6d

logging:
  level:
    org.springframework.security: INFO
    org.springframework.ai: INFO